import { FACES, POSITIONS } from "./types";

const ALL_DICE_POSITIONS = [
  [
    POSITIONS.FRONT,
    POSITIONS.TOP,
    POSITIONS.LEFT,
    POSITIONS.RIGHT,
    POSITIONS.BOTTOM,
    POSITIONS.BACK,
  ],
  [
    POSITIONS.RIGHT,
    POSITIONS.FRONT,
    POSITIONS.BOTTOM,
    POSITIONS.TOP,
    POSITIONS.BACK,
    POSITIONS.LEFT,
  ],
  [
    POSITIONS.TOP,
    POSITIONS.LEFT,
    POSITIONS.FRONT,
    POSITIONS.BACK,
    POSITIONS.RIGHT,
    POSITIONS.BOTTOM,
  ],
  [
    POSITIONS.BOTTOM,
    POSITIONS.LEFT,
    POSITIONS.BACK,
    POSITIONS.FRONT,
    POSITIONS.RIGHT,
    POSITIONS.TOP,
  ],
  [
    POSITIONS.RIGHT,
    POSITIONS.BACK,
    POSITIONS.TOP,
    POSITIONS.BOTTOM,
    POSITIONS.FRONT,
    POSITIONS.LEFT,
  ],
  [
    POSITIONS.BACK,
    POSITIONS.BOTTOM,
    POSITIONS.LEFT,
    POSITIONS.RIGHT,
    POSITIONS.TOP,
    POSITIONS.FRONT,
  ],
];

const ALL_FACES = [
  FACES.FIRST,
  FACES.SECOND,
  FACES.THIRD,
  FACES.FOURTH,
  FACES.FIFTH,
  FACES.SIXTH,
];

export { ALL_DICE_POSITIONS, ALL_FACES };
